### PR TITLE
new skuber version, new repo owner and maven release

### PR DESCRIPTION
**Pull request by hagay3**

### CODE REVIEW

**Comment by hagay3** [comment]
@Tim-Linschoten @jacum 
Please review, thanks !

**Comment by jacum** [comment]
Wow, cool. So you forked skuber and want us to switch to your fork with, ehm, 4 stars?
What do you mean by 'new repo owner'?

**Comment by jacum** [comment]
@hagay3 you don't seem to have changed anything in skuber but bumping the versions.
Why not submit your changes back to https://github.com/doriordan/skuber?

(I can't believe you're just seeking glory this way)

**Comment by hagay3** [comment]
Sorry for not adding details to this PR.
The skuber repo you have referenced is no longer maintained and accepting PRs.
https://github.com/doriordan/skuber

The new repo is also part of the official Kubernetes docs.
Screen Shot 2021-05-05 at 19 41 57

In addition, the latest release is not only bumping versions.
It also includes PRs that I merged and tested.

https://github.com/hagay3/skuber/pull/6
https://github.com/hagay3/skuber/pull/5
https://github.com/doriordan/skuber/pull/320

On a personal note,
I wanted to keep support and maintain skuber because I really liked this library and I'm using it on a daily basis.
I was really upset to see this library not being maintained.
This is why I forked it and I'm willing to keep maintaining the library.

Thank you for your understanding.

**Comment by jacum** [comment]
skuber is not abandoned as it seems, 25 days ago new version appeared. There seem to be no need to switch to another library source, as of now.

**Pull request closed without merging**
