### PR TITLE
Update to Scala 2.12.11 for better compilation speed

### PR DESCRIPTION
**Pull request by nightscape**

### CODE REVIEW

**Comment by jacum** [comment]
@nightscape could you please make sure your branch compiles? 
it is very welcome change

**Comment by nightscape** [comment]
@jacum done :smiley: 
I had forgotten to fix a deprecation.

**Comment by nightscape** [comment]
@jacum @FrancoAra contrary to what the Travis icon above says the build was successful.
Should be good to merge.

**Comment by jacum** [comment]
@nightscape it seems to be stuck, and I somehow can't kick travis to build once more

**Comment by jacum** [comment]
@nightscape we already merged bump to 2.12.11 to master (copied your changes verbatim), so this one could be closed
thanks for your contribution!

**Comment by nightscape** [comment]
@jacum perfect, thanks! Cross-building to Scala 2.13 is up next 😄

**Pull request closed without merging**
