### PR TITLE
WIP: PNML export

### PR DESCRIPTION
**Pull request by nightscape**
This PR adds experimental [PNML](http://www.pnml.org/) which allows using additional visualization and validation tools.
It's currently not yet exporting arcs and when opening the resulting file in the [ePNK editor](http://www.imm.dtu.dk/~ekki/projects/ePNK/index.shtml) it throws a `NullPointerException`.
Would you be interested in this?

### CODE REVIEW

**Comment by nikolakasev** [comment]
Hello Martin, that's one nifty contribution! Thanks for that. Let's suppose that we have the PNML support, what would that enable you to do? What do you have particularly in mind?

**Comment by nightscape** [comment]
Hi @nikolakasev, here's my main motivation for adding this:

1. It should allow using extended validation mechanisms like Linear Temporal Logic (LTL) as described e.g. [here](https://pdfs.semanticscholar.org/6c9e/164566be1899bd437b7d2942bf8fc234ea8f.pdf) 
I'm only beginning to dive into Petri Nets, so my plans might well be flawed 😉.
2. PNLM is afais the de-facto standard file format for Petri Nets ([it is/will be an ISO standard](https://en.wikipedia.org/wiki/Petri_Net_Markup_Language)) so hopefully a growing number of tools will build on this in the future.
3. It seemed to be little effort.
4. I'm evaluating different tools for productionizing Petri Nets, and the PR process of an open source library is a good indication of how likely it is to get bugs fixed, extensions merged, etc.

**Comment by nikolakasev** [comment]
Hi @nightscape, @Tim-Linschoten and I discussed your idea and we're looking forward to seeing what you will come up with! Would you also like to share any results from the PNML tools you plan to use?

**Comment by nightscape** [comment]
First success!
Here is the result of exporting the recipe from the `baas-client-example` as `.pnml` file, importing it into Eclipse with [`ePNK`](http://www.imm.dtu.dk/~ekki/projects/ePNK/index.shtml) and auto-arranging all nodes:
baas-client-example-pnml-epnk-export

Do you know if this is the correct transformation to a Petri Net for this example?

The `NullPointerException` I got earlier seems to have only occurred due to the fact that I had opened the file without putting it into an Eclipse project first.

I'm just adding a test that runs a validation against the generated PNML.
Do you have any other ideas of how to test, or anything else you'd like to have included in this PR?

**Comment by FrancoAra** [comment]
Hey @nightscape , cool contribution :) To make it usable by everyone could you add some user documentation? Including the why/what/how of this feature. You can find instructions on how to locally render our docs here: https://github.com/ing-bank/baker/blob/master/docs.md

**Comment by FrancoAra** [comment]
@nightscape Cool! Docs should help people use it :D, please let me know when this is no longer a "WIP" so that we can final review and merge it. I Hope you are safe and sound

**Comment by nightscape** [comment]
Hi @FrancoAra, I'm still trying to create an export that works with GreatSPN (one of the nicer editors for Petri Nets).
Probably the export should also be layed out properly, otherwise the graph is rather messy because all nodes are at the same position. Don't know how much work that is though...

**Comment by FrancoAra** [comment]
Sounds good! I'll be around

**Comment by FrancoAra** [comment]
By the way, I've been updating your branch with master, I hope it is not causing you inconveniences

**Comment by nightscape** [comment]
@nikolakasev @FrancoAra a nice small use case for this: Generate animated GIFs from an actual run of a Baker Petri Net via https://github.com/cucumber/petrinet

Animated Petri Net

The current state is that I wanted to put the graph layouting into its own library because it's completely independent of Baker and even scala-graph, but setting that up properly with automated builds and pushing to Maven central takes quite some time.

Would you be ok with a version where the layouting is incorporated into Baker and then I'll create another PR once the library is finished?
Otherwise this will hang for a while...

**Pull request closed without merging**
